default_platform(:ios)

api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
)

platform :ios do
    desc "Download certificates from the git"
    lane :syncCertificates do
        match(
            api_key: api_key,
            type: "appstore",
#             readonly: true,
            git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
            keychain_password: ENV["MATCH_PASSWORD"]
         )
        match(
           api_key: api_key,
           type: "development",
#            readonly: true,
           git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
           keychain_password: ENV["MATCH_PASSWORD"]
       )
    end
  desc "Push a new beta build to TestFlight"
  lane :beta do
        create_keychain(
            name: "keychain",
            password: "kaiji",
            default_keychain: true,
            unlock: true,
            timeout: 3600,
            lock_when_sleeps: false
        )
        match(
            keychain_name: "keychain",
            api_key: api_key,
            type: "appstore",
#             readonly: true,
            git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
            keychain_password: ENV["MATCH_PASSWORD"]
         )

    increment_build_number(xcodeproj: "wuchuheng.xcodeproj")
    build_app(
      scheme: "wuchuheng",
      xcodebuild_formatter: ""
    )

    upload_to_testflight
  end
end
