name: Appstore Deployment

on:
  push:
    tags:
      - v*

jobs:
  deploy_ios:
    name: Deploy build to TestFlight
    runs-on: macos-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv;
          echo 'eval "$(~/.rbenv/bin/rbenv init - bash)"' >> ~/.bashrc;
          rbenv install -l;
          rbenv install 2.7.5;
          rbenv global 2.7.5;
          rbenv local 2.7.5;
      #      - name: Configure env
#        run: |
#          envFile="fastlane/.env"
#          cat >> $envFile  <<EOL
#          APP_STORE_CONNECT_API_KEY_CONTENT="${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}"
#          EOL
#          cat >> $envFile  <<EOL
#          APP_STORE_CONNECT_API_ISSUER_ID="${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}"
#          EOL
#          cat >> $envFile  <<EOL
#          APP_STORE_CONNECT_API_KEY_ID="${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}"
#          EOL
#          cat >> $envFile  <<EOL
#          APP_IDENTIFIER="${{ secrets.APP_IDENTIFIER }}"
#          EOL
#          cat >> $envFile  <<EOL
#          GIT_AUTHORIZATION="${{ secrets.GIT_AUTHORIZATION }}"
#          EOL
#          cat >> $envFile  <<EOL
#          DEVELOPER_APP_ID="${{ secrets.DEVELOPER_APP_ID }}"
#          EOL
#          cat >> $envFile  <<EOL
#          PROVISIONING_PROFILE_SPECIFIER="${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}"
#          EOL
#          cat >> $envFile  <<EOL
#          MATCH_PASSWORD="${{ secrets.MATCH_PASSWORD }}"
#          EOL
#          cat >> $envFile  <<EOL
#          TEMP_KEYCHAIN_USER="${{ secrets.TEMP_KEYCHAIN_USER }}"
#          EOL
#          cat >> $envFile  <<EOL
#          FASTLANE_APPLE_ID="${{ secrets.FASTLANE_APPLE_ID }}"
#          EOL
#          cat >> $envFile  <<EOL
#          ITC_TEAM_ID="${{ secrets.ITC_TEAM_ID }}"
#          EOL
#          cat >> $envFile  <<EOL
#          DEVELOPER_PORTAL_TEAM_ID="${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}"
#          EOL
#          cat >> $envFile  <<EOL
#          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}"
#          EOL
#      - run: cat fastlane/.env
#      - name: Deploy iOS Beta to TestFlight via Fastlane
#        uses: maierj/fastlane-action@v1.4.0
#        with:
#          lane: closed_beta
#      - run: fastlane beta